name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3

      - name: Build Angular app
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: npm install, build
        run: |
          cd HackerNewsUI
          npm install
          npm run build -- --configuration production

      - name: Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PROUD_MEADOW_02249B60F }}
          action: "upload"
          app_location: "HackerNewsUI"
          output_location: "HackerNewsUI/dist"
          github_id_token: ${{ steps.idtoken.outputs.result }}
